[TASK] Add File Structure & Shadcn
StrandedDevcoon/Figma_Clone pull request #1
Opened 2024-02-18 22:13 UTC by StrandedDevcoon

2024-02-18 22:50 UTC, LvckyAPI requested changes
Sieht schon ganz ordentlich aus. Aber manche Dinge sind etwas merkwürdig.
Bitte nochmal drüber schauen. :)

2024-02-18 22:50 UTC, LvckyAPI commented on app/@liveblocks/react-comments/styles.css
?

2024-02-18 22:50 UTC, LvckyAPI commented on app/globals.css
>  }
komische Formatierung:

```css
* {
  font-family: work sans, sans-serif;
}
````

2024-02-18 22:50 UTC, LvckyAPI commented on app/globals.css
> +    @apply flex justify-between px-3 py-2 hover:bg-primary-grey-200 !important;
```suggestion
    @apply flex justify-between px-3 py-2 hover:bg-primary-grey-200 #{!important};
```

2024-02-19 08:27 UTC, StrandedDevcoon commented on app/@liveblocks/react-comments/styles.css
Habe ich vergessen zu unstagen. Wurde beim installieren mit generiert.

2024-02-19 08:30 UTC, StrandedDevcoon commented on liveblocks.config.ts
>      // from `userIds`. This info is used in comments, mentions etc.
Ist aus den Liveblocks DOCS, habe nicht daran gedacht die zu entfernen.

2024-02-19 08:56 UTC, LvckyAPI approved these changes
Ich denke, das passt so

2024-02-19 08:57 UTC, StrandedDevcoon commented on lib/canvas.ts
> +      // @ts-ignore
Wurde entfernt

2024-02-19 08:59 UTC, merged