[3-PR] Live User Reactions
StrandedDevcoon/Figma_Clone pull request #3
Opened 2024-02-19 18:59 UTC by StrandedDevcoon

- Eine Auswahlmöglichkeit von Emojis wurde implementiert.
- Der Benutzer kann Live ein Emoji auswählen, welcher mehrmals als Reaktion angezeigt wird.
- Als Externer Benutzer sieht man die Emojis des jeweils anderen Benutzers

2024-02-19 20:07 UTC, LvckyAPI requested changes
da sollte noch ein bisschen was angepasst werden ^^

2024-02-19 20:07 UTC, LvckyAPI commented on components/reaction/FlyingReaction.tsx
> +type Props = {
ich würde den Props den Namen der Komponente zuweisen `FlyingReactionProps`

2024-02-19 20:07 UTC, LvckyAPI commented on components/reaction/FlyingReaction.tsx
> +export default function FlyingReaction({x, y, timestamp, value}: Props) {
hier dementsprechend ändern nicht vegessen

2024-02-19 20:07 UTC, LvckyAPI commented on components/reaction/ReactionButton.tsx
> +            <ReactionButton reaction="👍" onSelect={setReaction} />
Vielleicht ein reaction ENUM basteln und von dort holen, kann man das besser lesen

2024-02-19 20:07 UTC, LvckyAPI commented on components/reaction/index.module.css
> +        transform: translate(0px, -300px);
rem angabe? 1rem = 16 px == -300px = -18.75rem

2024-02-19 20:07 UTC, LvckyAPI commented on components/reaction/index.module.css
> +        transform: translate(0px, -200px);
-12.5rem

2024-02-19 20:07 UTC, LvckyAPI commented on components/reaction/index.module.css
> +        transform: translate(50px, 0px);
3.125rem

2024-02-19 20:07 UTC, LvckyAPI commented on components/reaction/index.module.css
> +        transform: translate(100px, 0px);
6.25rem

2024-02-19 20:07 UTC, LvckyAPI commented on components/reaction/index.module.css
> +        transform: translate(-50px, 0px);
-3.125rem

2024-02-19 20:07 UTC, LvckyAPI commented on components/reaction/index.module.css
> +.leftRight0 {
irgendwie die benennung nicht schön, in klassen niemals zahlen so, vielleicht ausgeschrieben zero

2024-02-19 20:09 UTC, LvckyAPI commented on components/Live.tsx
>      }, [])
fixed in 945a90a60324371ddce779a16f3a5435823d4103

2024-02-19 20:09 UTC, LvckyAPI commented on components/Live.tsx
>      }, [])
fixed in 945a90a60324371ddce779a16f3a5435823d4103

2024-02-19 20:09 UTC, LvckyAPI commented on components/Live.tsx
> +    }, [cursorState.mode, setCursorState])
fixed in 945a90a60324371ddce779a16f3a5435823d4103

2024-02-19 21:55 UTC, LvckyAPI commented on components/reaction/ReactionButton.tsx
> +            <ReactionButton reaction="👍" onSelect={setReaction} />
create: https://git.lvckyworld.dev/nize.fm/nize-fm-api/-/blob/master/src/contracts/enum/http/responseCodeEnum.ts?ref_type=heads#L1

call: https://git.lvckyworld.dev/nize.fm/nize-fm-api/-/blob/master/src/routes/get/history.ts?ref_type=heads#L27

2024-02-20 12:45 UTC, StrandedDevcoon commented on components/Live.tsx
> +        if(cursorState.mode === CursorMode.Reaction && cursorState.isPressed && cursor) {
Ich habe mal recherchiert und tatsächlich ist die Reihenfolge korrekt. Es wird vorausgesetzt, dass die leichteste Bedingung zuerst geprüft wird und danach der Rest.

2024-02-20 14:30 UTC, LvckyAPI approved these changes
sieht gut aus, passt

2024-02-20 14:31 UTC, merged