[7-PR] Add Canvas and Blueprint for Real Time Using
StrandedDevcoon/Figma_Clone pull request #7
Opened 2024-02-22 07:27 UTC by StrandedDevcoon

- Ich habe das Canvas implementiert, damit man nun eine Fläche hat um darauf zu interagieren.
- Die Navbar wurde erweitert um Kommentare, Zeichnungen, Bilder etc. hinzuzufügen.
- Es wurde sowohl von shadcn/ui das Dropdown Menu und Button implementiert, als auch weitere Inhalte von Liveblocks.
- Blueprint wurde erstellt, damit als nächstes eine Real Time Interaktion möglich ist.

2024-02-22 10:06 UTC, LvckyAPI requested changes
Hier muss noch ein bisschen was angepasst werden.

2024-02-22 10:06 UTC, LvckyAPI commented on components/ui/dropdown-menu.tsx
> +      "z-50 min-w-[8rem] overflow-hidden rounded-md border bg-popover p-1 text-popover-foreground shadow-lg data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0
```suggestion
      "z-50 min-w-2 overflow-hidden rounded-md border bg-popover p-1 text-popover-foreground shadow-lg data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2",
```

`min-w-2` ist sogar exakt gleich

2024-02-22 10:06 UTC, LvckyAPI commented on components/ui/dropdown-menu.tsx
> +        "z-50 min-w-[8rem] overflow-hidden rounded-md border bg-popover p-1 text-popover-foreground shadow-md data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out
```suggestion
        "z-50 min-w-2 overflow-hidden rounded-md border bg-popover p-1 text-popover-foreground shadow-md data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2",
```

2024-02-22 10:06 UTC, LvckyAPI commented on components/ui/dropdown-menu.tsx
> +export {
Warum das export nicht direkt an den jeweiligen Konstanten dran?
Vielleicht in Zukunft besser für Lesbarkeit und wenn man was ändert oder löscht muss man nicht noch runter und das da auch noch austragen.

2024-02-22 18:02 UTC, StrandedDevcoon commented on components/ui/dropdown-menu.tsx
> +export {
Weil ich diese nur so am effizientesten exportieren kann

2024-02-23 08:13 UTC, LvckyAPI requested changes

2024-02-23 08:13 UTC, LvckyAPI commented on components/ui/select.tsx
> +
abstände zwischen den Konstanten wieder

2024-02-23 08:13 UTC, LvckyAPI commented on components/ui/select.tsx
> +        "relative z-50 max-h-96 min-w-[8rem] overflow-hidden rounded-md border bg-popover text-popover-foreground shadow-md data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=cl
```suggestion
        "relative z-50 max-h-96 min-w-2 overflow-hidden rounded-md border bg-popover text-popover-foreground shadow-md data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2",
```

2024-02-23 13:53 UTC, LvckyAPI approved these changes
Supi dupi

![a](https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExanZkeGpuOGY1MWR3OG5ocW92bGRlejMwMHFldXl6dXQyeGwzb2xxcCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Z9ElZWdwkFjrTyQqWF/giphy.gif)

2024-02-23 13:56 UTC, merged